title: 'Air Hockey Game '
description: Air Hockey game created during CSSIX
template:
  repo: air-hockey-game-template
  name: air-hockey-game
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
